.\" cgiFree - Frees the data structures
.\" Copyright (c) 1999,2007,8 by Martin Schulze <joey@infodrom.org>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation
.\" Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH cgiFree 3 "6 April 2008" "CGI Library" "Programmer's Manual"
.SH NAME
cgiFree \- Frees CGI data structure
.SH SYNOPSYS
.nf
.B #include <cgi.h>
.sp
.BI "void cgiFree (s_cgi *" parms );
.fi
.SH DESCRIPTION
This routine frees memory allocated by CGI parsing routines.
Temporary files from CGI file upload are also removed.
This is the opposite of
.BR cgiInit (3).

After this routine was called, no variables, cookies, files and no additional
header lines are available.  The result type is also reset to
"text/html".

.SH "AUTHOR"
This CGI library is written by Martin Schulze
<joey@infodrom.org>.  If you have additions or improvements
please get in touch with him.

.SH "SEE ALSO"
.BR cgiInit (3),
.BR cgiDebug (3),
.BR cgiHeader (3),
.BR cgiSetHeader (3),
.BR cgiSetType (3),
.BR cgiGetValue (3),
.BR cgiGetVariables (3)
.BR cgiGetCookie (3),
.BR cgiGetCookies (3).
