.\" cgiGetCookies - Returns a list of cookies
.\" Copyright (c) 1999,2007,8 by Martin Schulze <joey@infodrom.org>
.\" 
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" 
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software Foundation
.\" Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH cgiGetCookies 3 "6 April 2008" "CGI Library" "Programmer's Manual"
.SH NAME
cgiGetCookies \- Returns a list of cookies
.SH SYNOPSYS
.nf
.B #include <cgi.h>
.sp
.BI "char **cgiGetCookies (s_cgi *" parms );
.fi
.SH DESCRIPTION
This routine returns a NULL terminated array of names of cookies that were
transmitted by the client.  To get the value of a cookie you'll have
to use
.BR cgiGetCookie (3).
To free the memory allocated for the array, use
.BR cgiFreeList (3).
.SH "RETURN VALUE"
On success a NULL terminated array of strings is returned.  The last
element is set to NULL.  If an error occurred or if no cookies were
available NULL is returned.
.SH "AUTHOR"
This CGI library is written by Martin Schulze
<joey@infodrom.org>.  If you have additions or improvements
please get in touch with him.
.SH "SEE ALSO"
.BR cgiGetValue (3),
.BR cgiGetVariables (3),
.BR cgiGetCookie (3),
.BR cgiFreeList (3),
.BR cgiDebug (3),
.BR cgiHeader (3),
.BR cgiInit (3).
